apiVersion: batch/v1
kind: Job
metadata:
  name: spill-av
  namespace: tbd
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: spill-av
          image: "docker.pkg.github.com/navikt/helse-spill-av/spill-av:5758cab"
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 1024Mi
              cpu: 1000m
          volumeMounts:
            - mountPath: /var/run/secrets/nais.io/vault
              name: vault-secrets
              subPath: subpath/var/run/secrets/nais.io/vault
            - mountPath: /var/run/secrets/nais.io/service_user
              name: vault-secrets
              subPath: subpath/var/run/secrets/nais.io/service_user
            - mountPath: /etc/ssl/certs/java/cacerts
              name: ca-bundle
              subPath: ca-bundle.jks
          args:
            - dryRun=true
            - starttidspunkt=2021-03-24T10:55:00
          env:
            - name: VAULT_TOKEN_PATH
              value: /var/run/secrets/nais.io/vault/vault_token
            - name: KAFKA_RAPID_TOPIC
              value: tbd.rapid.v1
            - name: DATABASE_HOST
              value: a01dbfl039.adeo.no
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: spedisjon
            - name: VAULT_MOUNTPATH
              value: postgresql/prod-fss/
            - name: NAV_TRUSTSTORE_PATH
              value: /etc/ssl/certs/java/cacerts
            - name: NAV_TRUSTSTORE_PASSWORD
              value: changeme
      imagePullSecrets:
        - name: gpr-credentials
      initContainers:
        - name: vks-init
          image: navikt/vault-sidekick:v0.3.10-d122b16
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "1000m"
          volumeMounts:
            - mountPath: /var/run/secrets/nais.io/vault
              name: vault-secrets
              subPath: subpath/var/run/secrets/nais.io/vault
            - mountPath: /var/run/secrets/nais.io/service_user
              name: vault-secrets
              subPath: subpath/var/run/secrets/nais.io/service_user
          args:
            - -v=10
            - -logtostderr
            - -vault=https://vault.adeo.no
            - -one-shot
            - -save-token=/var/run/secrets/nais.io/vault/vault_token
            - -cn=secret:serviceuser/data/prod/srvspillav:dir=/var/run/secrets/nais.io/service_user,fmt=flatten
          env:
            - name: VAULT_AUTH_METHOD
              value: kubernetes
            - name: VAULT_SIDEKICK_ROLE
              value: spill-av
            - name: VAULT_K8S_LOGIN_PATH
              value: auth/kubernetes/prod/fss/login
      serviceAccount: podcreator
      serviceAccountName: podcreator
      volumes:
        - name: vault-secrets
          emptyDir:
            medium: Memory
        - name: ca-bundle
          configMap:
            defaultMode: 420
            name: ca-bundle-jks
      restartPolicy: Never

