name: master

on:
  push:
    branches:
    - master
env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/spill-av

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: create docker tag
      run: echo ::set-env name=TAG::$(echo ${{ github.sha }} | cut -c1-7)
    - name: test and build
      run: ./gradlew test build
      env:
        ORG_GRADLE_PROJECT_githubUser: x-access-token
        ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
    - name: build docker image
      run: docker build . --pull -t ${{ env.IMAGE }}:${{ env.TAG }}
    - name: push docker image
      run: |
        echo "$GITHUB_TOKEN" | docker login --username "$GITHUB_REPOSITORY" --password-stdin https://docker.pkg.github.com
        docker push ${{ env.IMAGE }}:${{ env.TAG }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
